services:
   postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    # env_file:
    #   - .env
    ports:
       - "5432:5432"
    volumes:
         - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: