services:
   db_inventory_bodegapp:
    image: postgres
    container_name: db_inventory_bodegapp
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
       - "5432:5432"
    volumes:
         - postgres_data:/var/lib/postgresql/data

  # cache_inventory_bodegapp:
  #   image: redis:7-alpine
  #   container_name: cache_inventory_bodegapp
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   command: redis-server --requirepass PsYsXm6C75j3ZYBrPApzqcTMz16Jkw
  #   volumes:
  #     - redis_data:/data

volumes:
  postgres_data:
  # redis_data: